sonar.projectKey=calculator-api
sonar.projectName=calculator-api
sonar.host.url=http://localhost:9000
sonar.login=sqp_b33374306b88dcdce6eb036d5c8100b23a9bb33b
sonar.sources=.
sonar.python.version=3.8.10
